package iviewxapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * @struct AOIRectangleStruct<br>
 * <br>
 * @brief Use this struct to customize the AOI position on screen. @ref AOIRectangleStruct<br>
 * is a part of @ref AOIStruct and can be defined with @ref iV_DefineAOI.<br>
 * <i>native declaration : C:\Program Files\SMI\iView X SDK\include\iViewXAPI.h:859</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AOIRectangleStruct extends Structure {
	public int x1;
	public int x2;
	public int y1;
	public int y2;
	public AOIRectangleStruct() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("x1", "x2", "y1", "y2");
	}
	public AOIRectangleStruct(int x1, int x2, int y1, int y2) {
		super();
		this.x1 = x1;
		this.x2 = x2;
		this.y1 = y1;
		this.y2 = y2;
	}
	public AOIRectangleStruct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AOIRectangleStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends AOIRectangleStruct implements Structure.ByValue {
		
	};
}
