package iviewxapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * @struct REDMonitorAttachedGeometryStruct<br>
 * <br>
 * @brief Deprecated. Please use @ref REDGeometryStruct instead.<br>
 * <i>native declaration : C:\Program Files\SMI\iView X SDK\include\iViewXAPI.h:2370</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class REDMonitorAttachedGeometryStruct extends Structure {
	public int stimX;
	public int stimY;
	public int redStimDistHeight;
	public int redStimDistDepth;
	public int redInclAngle;
	public REDMonitorAttachedGeometryStruct() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("stimX", "stimY", "redStimDistHeight", "redStimDistDepth", "redInclAngle");
	}
	public REDMonitorAttachedGeometryStruct(int stimX, int stimY, int redStimDistHeight, int redStimDistDepth, int redInclAngle) {
		super();
		this.stimX = stimX;
		this.stimY = stimY;
		this.redStimDistHeight = redStimDistHeight;
		this.redStimDistDepth = redStimDistDepth;
		this.redInclAngle = redInclAngle;
	}
	public REDMonitorAttachedGeometryStruct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends REDMonitorAttachedGeometryStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends REDMonitorAttachedGeometryStruct implements Structure.ByValue {
		
	};
}
