package de.unihannover.se.iviewxjava.iviewxapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * @struct DateStruct
<br>
 * <br>
 * @brief Use this struct to get the license due date of the device. Use the
<br>
 * function @ref iV_GetLicenseDueDate to update information in @ref DateStruct.<br>
 * <i>native declaration : C:\Program Files\SMI\iView X SDK\include\iViewXAPI.h:841</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DateStruct extends Structure {
	public int day;
	public int month;
	public int year;
	public DateStruct() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("day", "month", "year");
	}
	public DateStruct(int day, int month, int year) {
		super();
		this.day = day;
		this.month = month;
		this.year = year;
	}
	public DateStruct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DateStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends DateStruct implements Structure.ByValue {
		
	};
}
