package de.unihannover.se.iviewxjava.iviewxapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * @struct ImageStruct
<br>
 * <br>
 * @brief Use this struct to get raw eye image, raw scene video image, or
<br>
 * raw tracking monitor image. For receiving raw eye image (format: monochrome 8bpp)
<br>
 * use @ref iV_GetEyeImage, or set the eye image callback with @ref iV_SetEyeImageCallback.
<br>
 * For receiving raw scene video image (format: RGB 24bpp) use @ref iV_GetSceneVideo,
<br>
 * or set the scene video callback with @ref iV_SetSceneVideoCallback. For receiving
<br>
 * raw tracking monitor image (format: RGB 24bpp) use @ref iV_GetTrackingMonitor, or
<br>
 * set the tracking monitor callback with @ref iV_SetTrackingMonitorCallback.<br>
 * <i>native declaration : C:\Program Files\SMI\iView X SDK\include\iViewXAPI.h:820</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ImageStruct extends Structure {
	public int imageHeight;
	public int imageWidth;
	public int imageSize;
	/** C type : char* */
	public Pointer imageBuffer;
	public ImageStruct() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("imageHeight", "imageWidth", "imageSize", "imageBuffer");
	}
	/** @param imageBuffer C type : char* */
	public ImageStruct(int imageHeight, int imageWidth, int imageSize, Pointer imageBuffer) {
		super();
		this.imageHeight = imageHeight;
		this.imageWidth = imageWidth;
		this.imageSize = imageSize;
		this.imageBuffer = imageBuffer;
	}
	public ImageStruct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ImageStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends ImageStruct implements Structure.ByValue {
		
	};
}
