package de.unihannover.se.iviewxjava.iviewxapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * @struct REDStandAloneModeStruct
<br>
 * <br>
 * @brief Deprecated. Please use @ref REDGeometryStruct instead.<br>
 * <i>native declaration : C:\Program Files\SMI\iView X SDK\include\iViewXAPI.h:2344</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class REDStandAloneModeStruct extends Structure {
	public int stimX;
	public int stimY;
	public int stimHeightOverFloor;
	public int redHeightOverFloor;
	public int redStimDist;
	public int redInclAngle;
	public REDStandAloneModeStruct() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("stimX", "stimY", "stimHeightOverFloor", "redHeightOverFloor", "redStimDist", "redInclAngle");
	}
	public REDStandAloneModeStruct(int stimX, int stimY, int stimHeightOverFloor, int redHeightOverFloor, int redStimDist, int redInclAngle) {
		super();
		this.stimX = stimX;
		this.stimY = stimY;
		this.stimHeightOverFloor = stimHeightOverFloor;
		this.redHeightOverFloor = redHeightOverFloor;
		this.redStimDist = redStimDist;
		this.redInclAngle = redInclAngle;
	}
	public REDStandAloneModeStruct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends REDStandAloneModeStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends REDStandAloneModeStruct implements Structure.ByValue {
		
	};
}
