package de.unihannover.se.iviewxjava.iviewxapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * @struct SampleStruct
<br>
 * <br>
 * @brief This struct provides information about an eye data sample.
<br>
 * To update information in @ref SampleStruct use the function
<br>
 * @ref iV_GetSample or set the sample callback with @ref iV_SetSampleCallback.<br>
 * <i>native declaration : C:\Program Files\SMI\iView X SDK\include\iViewXAPI.h:497</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SampleStruct extends Structure {
	public long timestamp;
	/** C type : EyeDataStruct */
	public EyeDataStruct leftEye;
	/** C type : EyeDataStruct */
	public EyeDataStruct rightEye;
	public int planeNumber;
	public SampleStruct() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("timestamp", "leftEye", "rightEye", "planeNumber");
	}
	/**
	 * @param leftEye C type : EyeDataStruct<br>
	 * @param rightEye C type : EyeDataStruct
	 */
	public SampleStruct(long timestamp, EyeDataStruct leftEye, EyeDataStruct rightEye, int planeNumber) {
		super();
		this.timestamp = timestamp;
		this.leftEye = leftEye;
		this.rightEye = rightEye;
		this.planeNumber = planeNumber;
	}
	public SampleStruct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SampleStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends SampleStruct implements Structure.ByValue {
		
	};
}
