package de.unihannover.se.iviewxjava.iviewxapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * @struct TrackingStatusStruct
<br>
 * <br>
 * @brief This struct provides information about the relative eye ball position
<br>
 * within the tracking box. The information will be provided for each eye individually
<br>
 * as well as for the geographical center between both eyes. To update information in
<br>
 * @ref TrackingStatusStruct use the function @ref iV_GetTrackingStatus.<br>
 * <i>native declaration : C:\Program Files\SMI\iView X SDK\include\iViewXAPI.h:647</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TrackingStatusStruct extends Structure {
	public long timestamp;
	/** C type : EyePositionStruct */
	public EyePositionStruct leftEye;
	/** C type : EyePositionStruct */
	public EyePositionStruct rightEye;
	/** C type : EyePositionStruct */
	public EyePositionStruct total;
	public TrackingStatusStruct() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("timestamp", "leftEye", "rightEye", "total");
	}
	/**
	 * @param leftEye C type : EyePositionStruct<br>
	 * @param rightEye C type : EyePositionStruct<br>
	 * @param total C type : EyePositionStruct
	 */
	public TrackingStatusStruct(long timestamp, EyePositionStruct leftEye, EyePositionStruct rightEye, EyePositionStruct total) {
		super();
		this.timestamp = timestamp;
		this.leftEye = leftEye;
		this.rightEye = rightEye;
		this.total = total;
	}
	public TrackingStatusStruct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TrackingStatusStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends TrackingStatusStruct implements Structure.ByValue {
		
	};
}
