/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Luca Fuelbier' at '11.07.16 12:32' with Gradle 2.9
 *
 * @author Luca Fuelbier, @date 11.07.16 12:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
